const users = require('./users/users.service.js');
const payroll = require('./payroll/payroll.service.js');
const companies = require('./companies/companies.service.js');
const workers = require('./workers/workers.service.js');
const timesheets = require('./timesheets/timesheets.service.js');
const payrollRecords = require('./payroll-records/payroll-records.service.js');
const leaveTypes = require('./leave-types/leave-types.service.js');
const leaveBalances = require('./leave-balances/leave-balances.service.js');
const leaveRequests = require('./leave-requests/leave-requests.service.js');
const gazettedHolidays = require('./gazetted-holidays/gazetted-holidays.service.js');
const unitRecords = require('./unit-records/unit-records.service.js');
const clients = require('./clients/clients.service.js');
const projects = require('./projects/projects.service.js');
const positions = require('./positions/positions.service.js');
const departments = require('./departments/departments.service.js');
const jobBands = require('./job-bands/job-bands.service.js');
const jobGrades = require('./job-grades/job-grades.service.js');
const workerGroups = require('./worker-groups/worker-groups.service.js');
const tasks = require('./tasks/tasks.service.js');
const loans = require('./loans/loans.service.js');
const invoices = require('./invoices/invoices.service.js');
const compensationConfigs = require('./compensation-configs/compensation-configs.service.js');
const workerDocuments = require('./worker-documents/worker-documents.service.js');
const systemSettings = require('./system-settings/system-settings.service.js');
const emailService = require('./email/email.service.js');
const documentReminder = require('./document-reminder/document-reminder.service.js');
const uploads = require('./uploads/uploads.service.js');
const notifications = require('./notifications/notifications.service.js');
const qrCodes = require('./qr-codes/qr-codes.service.js');
const workerCheckin = require('./worker-checkin/worker-checkin.service.js');
const attendance = require('./attendance/attendance.service.js');
const weeklyTimesheetGenerator = require('../cron/weekly-timesheet-generator.js');

module.exports = function (app) {
  app.configure(users);
  app.configure(companies);
  app.configure(clients);
  app.configure(projects);
  app.configure(departments);
  app.configure(positions);
  app.configure(jobBands);
  app.configure(jobGrades);
  app.configure(workerGroups);
  app.configure(tasks);
  app.configure(loans);
  app.configure(invoices);
  app.configure(compensationConfigs);
  app.configure(workers);
  app.configure(workerDocuments);
  app.configure(systemSettings);
  app.configure(emailService);
  app.configure(documentReminder);
  app.configure(uploads);
  app.configure(notifications);
  app.configure(qrCodes);
  app.configure(attendance);
  app.configure(workerCheckin);
  app.configure(timesheets);
  app.configure(payrollRecords);
  app.configure(leaveTypes);
  app.configure(leaveBalances);
  app.configure(leaveRequests);
  app.configure(gazettedHolidays);
  app.configure(unitRecords);
  app.configure(payroll);

  // Cron jobs
  app.configure(weeklyTimesheetGenerator);
};

